service: serverless-task-manager-demo

custom:
  myStage: ${opt:stage, 'preprod'}
  region: ap-south-1
  projectsTableName: projects-table-${self:custom.myStage}
  tasksTableName: tasks-table-${self:custom.myStage}
  esbuild:
    bundle: true
    minify: false
    disableIncremental: true
    concurrency: 1

provider:
  name: aws
  runtime: nodejs16.x
  versionFunctions: false
  stage: ${self:custom.myStage}
  region: ${self:custom.region}
  apiGateway: 
    binaryMediaTypes:
      -'*/*'
  environment:
    TASKS_TABLE: ${self:custom.tasksTableName}
    PROJECTS_TABLE: ${self:custom.projectsTableName}
    QUEUE_URL: { Ref: TaskManagerQueue }

  # This section is used to configure permissions
  iamRoleStatements:
    - Effect: Allow
      Action:
        - ses:SendEmail
        - ses:SendRawEmail
      Resource:
        - "*"
    - Effect: Allow
      Action:
        - s3:*
        - sqs:*
        - sns:*
        - kms:*
      Resource: "*"
    # This will add dynamoDB permissions for the
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - "*"
  memorySize: 128
  # Setting a timeout of 15 minutes on all lambdas in this stack
  timeout: 900

plugins:
  - serverless-esbuild
  - serverless-offline

package:
  individually: true

functions:
  getProjects:
    handler: src/project/getProjects.handler
    timeout: 30
    events:
      - http:
          path: /projects
          method: get
          cors:
            maxAge: 3600
  getProject:
    handler: src/project/getProject.handler
    timeout: 30
    events:
      - http:
          path: /projects/{id}
          method: get
          cors:
            maxAge: 3600
  createProject:
    handler: src/project/createProject.handler
    timeout: 30
    events:
      - http:
          path: /projects
          method: post
          cors:
            maxAge: 3600
  updateProject:
    handler: src/project/updateProject.handler
    timeout: 30
    events:
      - http:
          path: /projects/{id}
          method: patch
          cors:
            maxAge: 3600
  deleteProject:
    handler: src/project/deleteProject.handler
    timeout: 30
    events:
      - http:
          path: /projects/{id}
          method: delete
          cors:
            maxAge: 3600
  getTasks:
    handler: src/task/getTasks.handler
    timeout: 30
    events:
      - http:
          path: /tasks
          method: get
          cors:
            maxAge: 3600
  getTask:
    handler: src/task/getTask.handler
    timeout: 30
    events:
      - http:
          path: /tasks/{id}
          method: get
          cors:
            maxAge: 3600
  createTask:
    handler: src/task/createTask.handler
    timeout: 30
    events:
      - http:
          path: /tasks
          method: post
          cors:
            maxAge: 3600
  updateTask:
    handler: src/task/updateTask.handler
    timeout: 30
    events:
      - http:
          path: /tasks/{id}
          method: patch
          cors:
            maxAge: 3600
  s3UploadValidate:
    handler: src/task/uploadToS3.handler
    timeout: 30
    events:
      - http:
          path: /uploadToS3/{id}
          method: post
          cors:
            maxAge: 3600
  deleteTask:
    handler: src/task/deleteTask.handler
    timeout: 30
    events:
      - http:
          path: /tasks/{id}
          method: delete
          cors:
            maxAge: 3600
  pushToQueue:
    handler: src/queue/pushQueue.handler
    timeout: 30
    events:
      - http:
          path: /pushQueue
          method: post
          cors:
            maxAge: 3600
  processQueue:
    handler: src/queue/processQueue.handler
    description: FIFO queue processing
    timeout: 900
    memorySize: 512
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - TaskManagerQueue
              - Arn
          batchSize: 1

resources:
  Resources:
    Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:service}-${self:custom.myStage}-attachment-buckets
    ProjectsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.projectsTableName}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
    TasksTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tasksTableName}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: projectId
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        GlobalSecondaryIndexes:
          - IndexName: task-project-index
            KeySchema:
              - AttributeName: projectId
                KeyType: HASH
              - AttributeName: id
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
    TaskManagerQueue:
      Type: 'AWS::SQS::Queue'
      Properties:
        QueueName: ${self:service}-${self:custom.myStage}-task-manager-queue.fifo
        VisibilityTimeout: 1800
        FifoQueue: true
