name: CD:- Cloudformation

on:
  workflow_call:
  push:
    branches:
      - main
      - develop

jobs:
  Deploy:
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      AWS_REGION: ap-south-1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v3.x
        env:
          STAGE: ${{ env.GITHUB_REF_SLUG }}
        
      - name: Install serverless dependency
        run: yarn install --frozen-lockfile
      - name: Package Functions
        run: npx serverless package
      - name: Deploy Functions - dev account
        if: ${{ (env.GITHUB_REF_SLUG == 'preprod') || (env.GITHUB_REF_SLUG == 'uat') }}
        run: npx serverless deploy --package .serverless --stage preprod
      - name: Deploy Functions - prod account
        if: ${{ (env.GITHUB_REF_SLUG == 'main') }}
        run: npx serverless deploy --package .serverless --stage prod
